# Use the official Python image
FROM python:3.8

# Set working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy all the files to the container
COPY . .

# Run the app with gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:8051", "app:app"]
